[project]
name = "llamaindex-task-timer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-index>=0.12.49",
    "llama-index-core>=0.12.49",
    "llama-index-llms-nebius>=0.1.2",
    "python-dotenv>=1.1.1",
]
