[project]
name = "pydantic-weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai>=0.4.2",
    "pydantic-ai-slim[duckduckgo]>=0.4.2",
    "python-dotenv>=1.1.1",
]
